### ISSUE TITLE
point multi-line text

### ISSUE THREAD

**Issue by CaverBruce** [richsmith/sexytopo#58] opened 2018-11-26 02:53 UTC
The point text entry dialog allows entry of multi-line text, new line being activated by using return key.  However the text is rendered as a single line.  Perhaps this is a bug?
I would prefer multi-line text to render as multi-line text.

**Comment by richsmith** [comment] 2019-07-08 21:11
Not a bug as such, just not handled that way by Android out of the box. Now fixed in 1.3.4 though.

**Closed by richsmith** 2019-07-08 21:11 UTC
