### ISSUE TITLE
Connecting a loop within a survey

### ISSUE THREAD

**Issue by tomfoord** [richsmith/sexytopo#111] opened 2019-08-04 13:46 UTC
I can't find any way of connecting a loop within a survey.

For example, consider a passage with a short oxbow. The main centreline is surveyed along the main passage. A side branch is then surveyed through the oxbow. This branch needs to be connected back into the main centreline at the station where the passages rejoin, thereby creating a small loop.
I can't find any way of creating this connection in SexyTopo. If I try to do it by renaming the final station in my oxbow (ie. give it the same name as the station it connects to in the main centreline) then SexyTopo tells me 'Station name must be unique'.

The only way I can think of doing it would be to create a completely separate survey for the oxbow (or even just for the final leg of the oxbow) and link the two surveys at both ends, but this seems a little excessive for a loop that may be only 3 or 4 legs in length.

Am I missing something?

**Comment by CaverBruce** [comment] 2019-08-04 19:33
While I am not opposed to the idea of closing loops in field data, it is something I have chosen specifically not to do.  PocketTopo can do it, but after a couple of trials I decided it is generally undesirable (just a personal preference).  
Reasons include such things as drawing registration with the survey leg if the closure distorts the network, and 'going to' a station and not really knowing which instance of a station you have selected.  My strong preference in field notes is to be always able to see the misclose, and draw tightly referenced to the misclosed legs.  Therion or other post processing software is the place to close loops.
My suggested user work-around is to either rename a station as say 1.7a (as a duplicate of 1.7) or to make a note to effect that 1.15 = 1.7 loop closure.

**Comment by tomfoord** [comment] 2019-08-05 13:22
Actually, I think Bruce makes a valid point, and I'm now tending to agree
with him (thanks Bruce!)
Rich, please consider this a non-issue for now.
Cheers
Tom

**Comment by richsmith** [comment] 2019-08-05 20:06
Cool. Andrew Atkinson had a similar view. I might get around to doing something with it some day but it's a low priority.

**Closed by richsmith** 2019-08-05 20:06 UTC
