### ISSUE TITLE
Data loss

### ISSUE THREAD

**Issue by WillHardie** [richsmith/sexytopo#40] opened 2018-04-29 14:16 UTC
I have had three crashes that left me with no data. It's a great app but not stable enough!

**Comment by richsmith** [comment] 2018-04-29 22:12
Hi Will

Thanks for the error report.

I appreciate it is frustrating if you've lost data. Unfortunately I can't do much about it without more information. It's next to impossible to fix any bug if I can't reproduce it.

Did you try restoring from autosave (File -> Restore Autosave)? This is supposed to protect your data in the event of a crash.

I don't seem to have received an Android error report with the crashes. It's very useful if you're able to submit the standard Android error report on a crash when prompted (if you're underground or otherwise out of signal it might not have got through even if you asked to submit it).

Failing that, do you have any more info about what you were doing when the crashes happened? This might give me some clue as to what happened.

Thanks
Rich

**Comment by richsmith** [comment] 2018-04-29 22:12
Also, thanks for the compliment :)

**Comment by WillHardie** [comment] 2018-04-30 05:59
Hi Rich
Thanks for taking the time to respond!
When it crashed I was surveying with DistoX with the app running on a Samsung
Galaxy J1 Mini (not the most powerful device... but cheap and light).
Taking straightforward station-to-station shots and splays, and working
from the data table screen. The screen went black and the app closed.
Previously I was using an older version of the app (probably a year old)
which also gave me intermittent bluetooth errors ("read failed socket might
closed").
Yesterday I updated it to the newest version (which I like even better) and
I no longer get bluetooth errors -- but the blackscreen crash happened
again.
I have noticed that data transfer can be very slow. When I take one
measurement, it transfers almost instantly. But when I take 5+ splays from
one station they start to back up, and it can take 10-20 seconds for each
new measurement to arrive in the app. Even taking three identical shots to
force a new station can take 30-40 seconds to transfer. Is this normal?
Next time I'll try the autosave; this time I went back to pen and paper
just to be safe.
It's a kickass cave, by the way. We just reached -465m and it's still
going... out of rope.
Best regards
Will

**Comment by richsmith** [comment] 2018-04-30 12:46
Thanks, but unfortunately not a lot to go on. The fact it crashed on the data screen is interesting... SexyTopo has been designed to work as much as possible in sketch view, so has had less testing in data view. I'll see if I can improve the error handling in this view when I get a minute.

Hopefully the next release or two will have better error reporting and more user-friendly autosave.

The data transfer speed limit does seem a little slow... to some extent this is just the limitations of the disto. I think it's about as fast as its competitors, but I'll take another look at the comms code when I add in calibration.

Good job on the cave! I'm using SexyTopo myself for surveying stuff but I'm not necessarily recommending people use it for important stuff yet because people (like yourself) are still finding bugs in it. If you do, though, I recommend saving regularly :)

**Comment by richsmith** [comment] 2019-01-19 12:45
I'm closing this because I've made autosave restore automatic and added some stability fixes.

The data transfer should be faster too.

**Closed by richsmith** 2019-01-19 12:45 UTC

**Comment by WillHardie** [comment] 2019-01-19 12:46
Great, many thanks. 
Will
